run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - github.com/spf13/viper.BindPFlag
      - (*github.com/spf13/viper.Viper).BindPFlag
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
        disabled: true
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
